---
title: "CodeBook"
author: "Barbara jesacher"
date: "27 2 2018"
output: html_document
---

## CodeBook

`data.txt` is a text file with space-seperated values.

The first row contains the names of the variables, which are described below.

### Variables

Each observation contains the variables for a given subject and activity.

- `Subjects` identifies the subject who performed the activity.
- `Activities` are `walk`, `walk_up`, `walk_down`, `sit`, `stand`, `lay`.

The columns contain the mean and standard deviation of:

- `tBodyAcc_mean_XYZ`
- `tBodyAcc_std_XYZ`
- `tGravityAcc_mean_XYZ`
- `tGravityAcc_std_XYZ`
- `tBodyAccJerk_mean_XYZ`
- `tBodyAccJerk_std_XYZ`
- `tBodyGyro_mean_XYZ`
- `tBodyGyro_std_XYZ`
- `tBodyGyroJerk_mean_XYZ`
- `tBodyGyroJerk_std_XYZ`
- `tBodyAccMag_mean`
- `tBodyAccMag_std`
- `tGravityAccMag_mean`
- `tGravityAccMag_std`
- `tBodyAccJerkMag_mean`
- `tBodyAccJerkMag_std`
- `tBodyGyroMag_mean`
- `tBodyGyroMag_std`
- `tBodyGyroJerkMag_mean`
- `tBodyGyroJerkMag_std`
- `fBodyAcc_mean_XYZ`
- `fBodyAcc_std_XYZ`
- `fBodyAcc_meanFreq_XYZ`
- `fBodyAccJerk_mean_XYZ`
- `fBodyAccJerk_std_XYZ`
- `fBodyAccJerk_meanFreq_XYZ`
- `fBodyGyro_mean_XYZ`
- `fBodyGyro_std_XYZ`
- `fBodyGyro_meanFreq_XYZ`
- `fBodyAccMag_mean`
- `fBodyAccMag_std`
- `fBodyAccMag_meanFreq`
- `fBodyBodyAccJerkMag_mean`
- `fBodyBodyAccJerkMag_std`
- `fBodyBodyAccJerkMag_meanFreq`
- `fBodyBodyGyroMag_mean`
- `fBodyBodyGyroMag_std`
- `fBodyBodyGyroMag_meanFreq`
- `fBodyBodyGyroJerkMag_mean`
- `fBodyBodyGyroJerkMag_std`
- `fBodyBodyGyroJerkMag_meanFreq`

where `t` denotes the time domain and `f` the frequency domain.
 
The transformations made to clean the data are described in the readMe.